;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; NSBB Autogenerated Assembly                     ;
; Generated by the PYTHON implementation of NSBB. ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

section .text
extern printf
extern _exit
global main
main:
	enter 0, 0
	mov rax, 34
	call __stk_push
	mov rax, 35
	call __stk_push
	call __stk_pop
	mov rdi, rax
	call __stk_pop
	add rax, rdi
	call __stk_push
	leave
	ret

	; Fallthrough in case function doesn't use RETURN.
	leave
	ret

__stk_push:
	enter 0, 0
	push rax
	push rdi
	mov rdi, [__stk_ptr]
	mov [__stk+rdi], rax
	add rdi, 8
	mov [__stk_ptr], rdi
	pop rdi
	pop rax
	leave
	ret

__stk_pop:
	enter 0, 0
	push rdi
	mov rdi, [__stk_ptr]
	sub rdi, 8
	mov rax, [__stk+rdi]
	mov [__stk_ptr], rdi
	pop rdi
	leave
	ret

__stk_peek:
	enter 0, 0
	mov rax, [__stk+rdi*8]
	leave
	ret

section .data
__stk_ptr: dq 0
section .bss
__stk: resq 2048
